### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by JohnnyTheBobo** [Yannick-Apostel/WWM#8]
Anscheinend sind hier .dia Dateien nicht erlaubt.

![Image](https://github.com/Yannick-Apostel/WWM/assets/152901937/30d9dd08-ea4e-43f6-a821-ba4f56581f4f)
![Image](https://github.com/Yannick-Apostel/WWM/assets/152901937/a2c3d7b0-69dd-43fd-9398-dba4f3a10d73)

**Comment by Yannick-Apostel** [comment]
uploaded on main
